version: "2"
services:
  api:
    container_name: wichteln_backend
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
    volumes:
      - /services/wichtelserver/api:/data/repo
  mongo:
    container_name: mongo
    image: mongo
    environment: 
      - MONGO_INITDB_DATABASE=wichteln
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"

