version: "3"
services:
  wichtel-api:
    container_name: wichteln_backend
    restart: always
    build: .
    environment:
     - SMTP_PASSWORD=
     - SMTP_USER=
     - SMTP_SENDER_MAIL=
     - SMTP_HOST=
     - SMTP_PORT=
     - JWT_VERIFY_KEY=
     - VUE_APP_API_ENDPOINT=
     - JWT_SECRET_KEY=
     - MONGODB_URI=
    ports:
      - "3000:3000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wichteln-http.entrypoints=web"
      - "traefik.http.routers.wichteln-http.rule=Host(`wichteln.wagner-labs.com`)"
      - "traefik.http.routers.wichteln.entrypoints=websecure"
      - "traefik.http.routers.wichteln.rule=Host(`wichteln.wagner-labs.com`)"
      - "traefik.http.routers.wichteln.tls=true"
      - "traefik.http.routers.wichteln.tls.certresolver=http"
      - "traefik.docker.network=proxy"
    volumes:
      - ./wichtelserver/api:/data/repo

